name: Java application

on:
  push:
    branches: [ "master" ]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - name: checking out source code
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B compile --file pom.xml
  
  security-check:
    runs-on: ubuntu-latest
    needs: compile # so that security-check job runs after compile job
    steps:
      - name: checkout source code
        uses: actions/checkout@v4

      - name: Installing trivy setup
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update -y
          sudo apt-get install -y trivy

      - name: running Trivy
        run: trivy fs --output trivy-report.json --format table .

      - name: Installing git leaks
        run: sudo apt install gitleaks -y
        
      - name: running git leaks
        run: gitleaks detect source . -r git-leaks-report.json -f json

